[project]
name = "dave3625-host-2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.30.1",
    "jupyter>=1.1.1",
]

[tool.uv.workspace]
members = [
    "Dave3625-Host-2025/lab0",
    "lab3",
]
